live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.normal]
family = "Maple Mono SC NF"
style = "Regular"

[[keyboard.bindings]]
chars = "\u0002,"
key = "Comma"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002s"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00027"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00028"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00029"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002L"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002["
key = "LBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002p"
key = "LBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002%"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002\""
key = "D"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002d"
key = "W"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002n"
key = "RBracket"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = """
\u001B:w
"""
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002!"
key = "T"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002x"
key = "X"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002z"
key = "Z"
mods = "Command"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.85

[window.padding]
x = 18
y = 16
